language: node_js
node_js: stable

cache:
  directories:
    - node_modules

before_deploy:
  - npm run generateDictionary
  - npm run build

script:
  - npm test
  - npm run coveralls

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
